apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: titan-exchange
  labels:
    app.kubernetes.io/name: titan-exchange
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app: titan-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
